"""Layer 2 modeling package."""

from .execution import (
    JobExecutionResult,
    create_emissions_tracker,
    cpu_burn,
    make_job_tracker_factory,
    measure_job_with_codecarbon,
    parallel_cpu_job,
    run_real_job,
)
from .emissions import (
    DEFAULT_POWER_MODEL,
    JobEmissionEstimate,
    PowerModel,
    annotate_jobs_with_carbon_scores,
    average_carbon_intensity,
    estimate_energy_kwh,
    estimate_job_emissions,
    estimate_power_watts,
    score_job,
)
from .timeslots import (
    DEFAULT_CAPACITY_PER_HOUR,
    DEFAULT_HORIZON_HOURS,
    TimeSlot,
    allocate,
    capacity_array,
    check_fit,
    get_timeslot_info,
    make_capacity_array,
    make_timeslot_array,
    reset_capacity,
)

__all__ = [
    "DEFAULT_CAPACITY_PER_HOUR",
    "DEFAULT_HORIZON_HOURS",
    "DEFAULT_POWER_MODEL",
    "JobExecutionResult",
    "JobEmissionEstimate",
    "PowerModel",
    "TimeSlot",
    "allocate",
    "annotate_jobs_with_carbon_scores",
    "average_carbon_intensity",
    "capacity_array",
    "check_fit",
    "create_emissions_tracker",
    "cpu_burn",
    "make_job_tracker_factory",
    "estimate_energy_kwh",
    "estimate_job_emissions",
    "estimate_power_watts",
    "get_timeslot_info",
    "make_capacity_array",
    "make_timeslot_array",
    "measure_job_with_codecarbon",
    "parallel_cpu_job",
    "reset_capacity",
    "run_real_job",
    "score_job",
]
